AWSTemplateFormatVersion: 2010-09-09
Description: Alert Logic Cross-Account Role for Cloud Defender. Creates IAM role/policy.
Parameters:
  AlertLogicDatacenter:
    Description: Alert Logic Datacenter into which your account was deployed.
    AllowedValues:
      - US
      - EU
    Default: US
    Type: String
  ExternalID:
    Description: >-
      A unique identifier that is used by AlertLogic when assuming roles in the
      account. This is entered into the Alert Logic Portal later on. More
      information can be found on the following page in AWS's IAM Documentation:
      http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html
    AllowedPattern: '[\w+=,.@:\/-]*'
    ConstraintDescription: >-
      The format for this parameter is a string of characters consisting of
      2-1224 upper and lower case alphanumeric characters with no spaces. You
      can also include underscores or any of the following characters: =,.@:\/-
    MinLength: 2
    MaxLength: 1224
    Type: String
    NoEcho: "true"
  KMSKey:
    Description: ARN of the KMS key used to encrypt the CloudTrail. If you are use centralized CloudTrail, enter the KMS key on the Receiving CFT instead of in this CFT.
    Type: String
    Default: ""
Mappings:
  AlertLogic:
    Datacenter:
      US: "arn:aws:iam::733251395267:root"
      EU: "arn:aws:iam::857795874556:root"
Conditions:
  NoKMS: !Equals
    - ""
    - !Ref KMSKey
Resources:
  AlertLogicRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref ExternalID
            Effect: Allow
            Principal:
              AWS:
                - !FindInMap
                  - AlertLogic
                  - Datacenter
                  - !Ref AlertLogicDatacenter
            Sid: ""
        Version: 2012-10-17
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - autoscaling:Describe*
                  - cloudformation:DescribeStack*
                  - cloudformation:GetTemplate
                  - cloudformation:ListStack*
                  - cloudfront:Get*
                  - cloudfront:List*
                  - cloudwatch:Describe*
                  - config:DeliverConfigSnapshot
                  - config:Describe*
                  - config:Get*
                  - config:ListDiscoveredResources
                  - cur:DescribeReportDefinitions
                  - directconnect:Describe*
                  - dynamodb:ListTables
                  - ec2:Describe*
                  - ecs:Describe*
                  - ecs:List*
                  - elasticbeanstalk:Describe*
                  - elasticache:Describe*
                  - elasticloadbalancing:Describe*
                  - elasticmapreduce:DescribeJobFlows
                  - events:Describe*
                  - events:List*
                  - glacier:ListVaults
                  - guardduty:Get*
                  - guardduty:List*
                  - kinesis:Describe*
                  - kinesis:List*
                  - kms:DescribeKey
                  - kms:GetKeyPolicy
                  - kms:GetKeyRotationStatus
                  - kms:ListAliases
                  - kms:ListGrants
                  - kms:ListKeys
                  - kms:ListKeyPolicies
                  - kms:ListResourceTags
                  - lambda:List*
                  - logs:Describe*
                  - rds:Describe*
                  - rds:ListTagsForResource
                  - redshift:Describe*
                  - route53:GetHostedZone
                  - route53:ListHostedZones
                  - route53:ListResourceRecordSets
                  - sdb:DomainMetadata
                  - sdb:ListDomains
                  - sns:ListSubscriptions
                  - sns:ListSubscriptionsByTopic
                  - sns:ListTopics
                  - sns:GetEndpointAttributes
                  - sns:GetSubscriptionAttributes
                  - sns:GetTopicAttributes
                  - s3:ListAllMyBuckets
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:GetBucket*
                  - s3:GetLifecycleConfiguration
                  - s3:GetObjectAcl
                  - s3:GetObjectVersionAcl
                  - tag:GetResources
                  - tag:GetTagKeys
                  - workspaces:Describe*
                  - workspaces:List*
                Effect: Allow
                Resource: "*"
                Sid: EnabledDiscoveryOfVariousAWSServices
              - Action:
                  - iam:Get*
                  - iam:List*
                  - iam:GenerateCredentialReport
                Effect: Allow
                Resource: "*"
                Sid: EnableInsightDiscovery
              - Action:
                  - cloudtrail:DescribeTrails
                  - cloudtrail:GetEventSelectors
                  - cloudtrail:GetTrailStatus
                  - cloudtrail:ListPublicKeys
                  - cloudtrail:ListTags
                  - cloudtrail:LookupEvents
                  - cloudtrail:StartLogging
                  - cloudtrail:UpdateTrail
                Effect: Allow
                Resource: "*"
                Sid: EnableCloudTrailIfAccountDoesntHaveCloudTrailsEnabled
              - Action:
                  - s3:CreateBucket
                  - s3:PutBucketPolicy
                  - s3:DeleteBucket
                Effect: Allow
                Resource: arn:aws:s3:::outcomesbucket-*
                Sid: CreateCloudTrailS3BucketIfCloudTrailsAreBeingSetupByAlertLogic
              - Action:
                  - sns:CreateTopic
                  - sns:DeleteTopic
                Effect: Allow
                Resource: arn:aws:sns:*:*:outcomestopic
                Sid: CreateCloudTrailsTopicTfOneWasntAlreadySetupForCloudTrails
              - Action:
                  - sns:addpermission
                  - sns:gettopicattributes
                  - sns:listtopics
                  - sns:settopicattributes
                  - sns:subscribe
                Effect: Allow
                Resource: arn:aws:sns:*:*:*
                Sid: MakeSureThatCloudTrailsSnsTopicIsSetupCorrectlyForCloudTrailPublishingAndSqsSubsription
              - Action:
                  - sqs:CreateQueue
                  - sqs:DeleteQueue
                  - sqs:SetQueueAttributes
                  - sqs:GetQueueAttributes
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueUrl
                Effect: Allow
                Resource: arn:aws:sqs:*:*:outcomesbucket*
                Sid: CreateAlertLogicSqsQueueToSubscribeToCloudTrailsSnsTopicNotifications
              - Action:
                  - sqs:ListQueues
                Effect: Allow
                Resource: "*"
                Sid: BeAbleToListSQSForCloudTrail
              - Action:
                  - ec2:GetConsoleOutput
                  - ec2:GetConsoleScreenShot
                  - ec2:StartInstances
                  - ec2:StopInstances
                  - ec2:TerminateInstances
                Condition:
                  StringEquals:
                    ec2:ResourceTag/AlertLogic: Security
                Effect: Allow
                Resource: arn:aws:ec2:*:*:instance/*
                Sid: EnableAlertLogicApplianceStateManagement
              - Action:
                  - autoscaling:UpdateAutoScalingGroup
                Condition:
                  StringEquals:
                    ec2:ResourceTag/AlertLogic: Security
                Effect: Allow
                Resource: arn:aws:autoscaling:*:*:autoScalingGroup/*
                Sid: EnableAlertLogicAutoScalingGroupManagement
              - Action: kms:Decrypt
                Sid: AllowDecryptOfCloudTrailKey
                Effect: Allow
                Resource:
                  !If [
                    NoKMS,
                    "arn:aws:kms:*:*:key/nonexistent_key",
                    !Ref KMSKey,
                  ]
            Version: "2012-10-17"
          PolicyName: alertlogic-clouddefender-iam-policy
    Type: "AWS::IAM::Role"
Outputs:
  ExternalID:
    Description: External ID used by Alert Logic to assume your new Cross-Account IAM role.
    Value: !Ref ExternalID
  RoleARN:
    Description: Amazon Resource Name of your new Cross-Account IAM Role.
    Value: !GetAtt
      - AlertLogicRole
      - Arn